### PR TITLE
Hot fix:  resolved merge conflicts, updated UI breaking and updated props docs(rectified redundant code).

### LINKED ISSUE #75: 🐛 Bug:  Error log is unaligned and breaking the UI of playground. (Need to make a hot-fix) for all components.
**Explain what you did (Required)**

- I intentionally tried to create a compilation error on the playground.
- The error popup was found breaking UI for the playground application.

**Expected behavior (Required)**

- The error component should not break the UI.
- This will cause the user un-comfortable while using the playground web app.

**Describe the bug (Required)**

- The bug is breaking the UI of the `Playground`.

**To Reproduce (Required)**

https://react-native-elements.js.org/#/icon'

- Steps
1. Go to 'https://react-native-elements.js.org/#/icon'
2. Try to create typos 'in the text editor of the playground'.
3. Scroll down to 'Look to the top error components'

**Screenshots (Required)**

Screenshot from 2021-03-16 12-32-48

Expected: (screenshot)
 
Screenshot from 2021-03-16 12-43-31

@pranshuchittora, and @flyingcircle... I have started working on the bug to be fixed as early as possible?

**Any suggestions are welcome** @flyingcircle @pranshuchittora

### PR DESCRIPTION
**Pull request by Uyadav207**
**What kind of change does this PR introduce?**

- Fix made for conflict at #53 and #76 .....

**Did you add tests for your changes?**

- Not required...

**Summary**

- After the merge of #15.... there was some conflict occurred resolved that conflict in this PR.

## ERROR RESOLVED IS SHOWN BELOW

**Does this PR introduce a breaking change?**

- No breaking changes are involved.

**Other information**

- Also removed UI breaking.

### CODE REVIEW

**Comment by Uyadav207** [comment]
@pranshuchittora, The checks are failing because.... 

when tried to update the `Props` folder... it is not pushing....then after looking at this issue... I found that you have pushed the Props folder in `.gitignore`, That is why ... the checks are not passing as there is no prop folder found.

- What to do now?
- may I remove it from `.gitignore`?
- This is also causing compilation error on `development` in the `local host`....

**Comment by Uyadav207** [comment]
please let me know the changes... I will be doing it ASAP...

**Review by shivambalwani — APPROVED** [review]

**Review by jugshaurya — APPROVED** [review]

**Comment by pranshuchittora** [comment]
@Uyadav207 this is not required as #15 introduces remote docs for always up-to-dated docs.

**Comment by Uyadav207** [comment]
ok Got it... @pranshuchittora ... Also The UI for error render is quite buggy may, I give the PR for that instead.

**Comment by Uyadav207** [comment]
As that changes were included ... in this PR also but no worries

**Comment by pranshuchittora** [comment]
Sure, Feel free to open a new PR if this can't be updated.

**Comment by Uyadav207** [comment]
Screenshot from 2021-03-26 23-58-19


@pranshuchittora, pls help me how can I resolve this??clear

**Comment by Uyadav207** [comment]
@pranshuchittora, please have a look...

Screenshot from 2021-03-27 00-14-24

- after running npm prepare... i.e injecting props... The error is still there... Might be the Case the directory is not found.

**Comment by jugshaurya** [comment]
> @pranshuchittora, please have a look...
> 
> Screenshot from 2021-03-27 00-14-24
> 
> * after running npm prepare... i.e injecting props... The error is still there... Might be the Case the directory is not found.
> * current import STATEMENT
>   Screenshot from 2021-03-27 00-16-00

@Uyadav207 , problem is solvable when you run npm i, npm i is running injectProps.js, which is adding Props folder to the appropritate folder. So wait for the https://github.com/react-native-elements/playground/pull/97 to be merged and then run npm i once more to get folder into the codebase/workspace

**Comment by Uyadav207** [comment]
> > @pranshuchittora, please have a look...
> > Screenshot from 2021-03-27 00-14-24
> > 
> > * after running npm prepare... i.e injecting props... The error is still there... Might be the Case the directory is not found.
> > * current import STATEMENT
> >   Screenshot from 2021-03-27 00-16-00
> 
> @Uyadav207 , problem is solvable when you run `npm i`, `npm i` is running injectProps.js, which is adding Props folder to the appropritate folder. So wait for the #97 to be merged and then run npm i once more to get folder into the codebase/workspace

Resolved.. The folder was injected ... but in wrong sub folder

**Pull request closed without merging**
