### PR TITLE
fix: Drawer navigation bug complete fix made

### PR DESCRIPTION
**Pull request by Uyadav207**
@pranshuchittora, the issue #20 , wasn't completely fixed by the **PR #21** .

**Issues still occuring**

- on clicking **the links**, the drawer was navigating to the link, but not closing after navigating.

**I have fixed  the bug completely, Kindly check.**

### screen gif after fix

captured

- [x] checked the bug on ios and android as well

### CODE REVIEW

**Comment by ankushdutt** [comment]
This change will break the desktop version. There is undesirable toggling of nav drawer whenever clicked on drawer links/items.

**Comment by Uyadav207** [comment]
> This change will break the desktop version. There is undesirable toggling of nav drawer whenever clicked on drawer links/items.

Thanks for your concern

but I have rechecked the changes, they are working well in desktop(browsers) as well as smart phones.

- There was a need of onClick handler that on clicking will redirect the user to particular components page. **Also Toggle Back the Drawer Navigation to its previous state**

@pranshuchittora please review the PR, and confirm that the bug is completely fixed or not.

Thanks.

**Comment by Uyadav207** [comment]
Thanks @ankushdutt, :)

### **Previous issue**

ss

###  **After resolving** (DESKTOP)

captured (1)

###  **After resolving** (SMART PHONES)

smart

**Review by tewarig — COMMENTED** [review]
Great work

**Comment by pranshuchittora** [comment]
LGTM :+1: 
Thanks @Uyadav207

**Comment by Uyadav207** [comment]
Happy to contribute @pranshuchittora. :)

**Pull request merged**
