### PR TITLE
feature: Eslint Added, code formated, made codebase consistent

### PR DESCRIPTION
**Pull request by jugshaurya**
work in progress.
- [x] Basic Eslint configs
- [x] eslint react plugin
- [x] eslint Json support addition
- [x] eslint a11y check plugin
- [x] Fix CI checks 

@pranshuchittora please review

### CODE REVIEW

**Comment by jugshaurya** [comment]
@pranshuchittora , added eslint , please review, require some more specific changes let me know , happy to help

**Comment by jugshaurya** [comment]
@flyingcircle, please review

**Comment by flyingcircle** [comment]
merge conflict.

**Comment by jugshaurya** [comment]
@flyingcircle , done conflict resolved

**Pull request merged**
