### PR TITLE
chore: add Pull Request Template

### PR DESCRIPTION
**Pull request by jalajcodes**
Added a pull request template.

Use to guide contributors to fill PR descriptions and make life a little easier for reviewers.

### CODE REVIEW

**Comment by Uyadav207** [comment]
@jalajcodes i have already 12 hours ago, raised an issue for this, also updated my PR branch for the same. waiting for the mentor to assign me the task. 

please raise an issue before  raising a PR. and abide by the **Contributions** **guide**

**Comment by Uyadav207** [comment]
I request you to work on a new issue and do not spam other's Task. please close the PR ASAP

Thanks. :)

@jalajcodes

**Comment by Uyadav207** [comment]
@jalajcodes, #24 Already raised an issue.

**Comment by Uyadav207** [comment]
#36

**Comment by pranshuchittora** [comment]
Already reviewing https://github.com/react-native-elements/playground/pull/36

**Pull request closed without merging**
