### PR TITLE
chore: add Loading Component in fallbacks

### PR DESCRIPTION
**Pull request by jugshaurya**
- Adding Loading Spinner(Material UI) to fallbacks @ all places.
- Also added MaterialUI snippents recommendation in .vscode/extension.json

@pranshuchittora please review.

### CODE REVIEW

**Comment by pranshuchittora** [comment]
LGTM.
Pls fix the CI

**Comment by jugshaurya** [comment]
> LGTM.
> Pls fix the CI

Build is failing
ppp
 because of missing package v8

looking into the problem

**Comment by jugshaurya** [comment]
Solution: Adding a browser env preset into .babelrc file or in config-overrides file
@pranshuchittora please review

**Comment by jugshaurya** [comment]
@flyingcircle, please review

**Pull request merged**
