### PR TITLE
fixed linting issues

### PR DESCRIPTION
**Pull request by abhishekkumar08**
**What kind of change does this PR introduce?**
fixed linitng issues of ```src/components``` folder

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**
The project contains a lot of linting and a11y issues, wanted to work on them.

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by abhishekkumar08** [comment]
@pranshuchittora Is the PR okay, if it is can I work on all the issues of the codebase?

**Comment by pranshuchittora** [comment]
Is this related to unused imports ?

**Comment by abhishekkumar08** [comment]
Yes, the unused imports. If all the changes are correct should I proceed to the other files?

**Comment by pranshuchittora** [comment]
Thanks

**Pull request merged**
