### PR TITLE
update footer styling - issue#3

### PR DESCRIPTION
**Pull request by ARJUN-SABU**
Fixed issue#3:
Changed inline css to external css in the complete footer section. Also added css transitions on the footer images to improve the UI.

### CODE REVIEW

**Comment by pranshuchittora** [comment]
https://github.com/react-native-elements/playground/pull/23#issuecomment-795542374

**Comment by ARJUN-SABU** [comment]
> [#23 (comment)](https://github.com/react-native-elements/playground/pull/23#issuecomment-795542374)

Ok, changing the regular css stylesheet to css module stylesheet

**Comment by pranshuchittora** [comment]
LGTM :+1: 
 can you remove the lock file or resolve the conflicts

**Review by pranshuchittora — APPROVED** [review]

**Comment by ARJUN-SABU** [comment]
> LGTM 👍
> can you remove the lock file or resolve the conflicts

Ok let me try

**Comment by ARJUN-SABU** [comment]
Sorry, but package-lock.json conflict is not getting resolved. I tried manually removing it from temp branch and then pushing back to git hub, but it again shows up. Any help on this?

**Comment by ARJUN-SABU** [comment]
Conflict has been removed by deleting the package-lock.json file

**Comment by pranshuchittora** [comment]
Thanks

**Pull request merged**
