### PR TITLE
fix loading style in socialicon

### LINKED ISSUE #51: SocialIcon: original icon is visible when loading
image

To reproduce:
* Visit https://react-native-elements.js.org/#/social-icon
* Check the loading checkbox

Expected Behavior:
* Only the loading icon should be visible

### PR DESCRIPTION
**Pull request by ankushdutt**
fixes #51 

image

### CODE REVIEW

**Review by Uyadav207 — COMMENTED** [review]
Screenshot from 2021-03-13 16-25-00

**Problem**
- The icon still shows beside the loading icon.
- when `onLoading: {true}` && `icon: {true}` then icon and blank svg img is visible.

**Possible Solution**
- please try to use `Conditional Rendering`.
- This can be done using a `ternary operator`.

**Comment by ankushdutt** [comment]
fixed the loading issue here (https://github.com/react-native-elements/react-native-elements/pull/2846)
Added the `activityIndicatorStyle` for socialicons to the playground here, so we can merge this one too 
@pranshuchittora

**Comment by pranshuchittora** [comment]
@ankushdutt thanks for finding the issue and fixing the same in the core.
Is `activityIndicatorStyle` is a new prop ?

If yes, then pls add the same to the docs (https://github.com/react-native-elements/react-native-elements/tree/next/website/docs/props) so that it can be automatically pulled in the Playground via #15

**Comment by ankushdutt** [comment]
> Is `activityIndicatorStyle` is a new prop ?

No, it was already present in the codebase of React Native Core (I haven't added them in my fix there). Though, its not present in [SocialIcon docs](https://reactnativeelements.com/docs/social_icon#props)

Alright, I'll make a PR for the missing props in the core.

**Comment by pranshuchittora** [comment]
Did you made a PR for the `activityIndicatorStyle`

**Comment by ankushdutt** [comment]
> Did you made a PR for the `activityIndicatorStyle`

Yes, here: https://github.com/react-native-elements/react-native-elements/pull/2946

**Pull request merged**
