### PR TITLE
fix: made button and avatar component functional

### PR DESCRIPTION
**Pull request by nlok5923**
fixes part of: #3 
changes:
- made avatar and button component functional

### CODE REVIEW

**Comment by Devesh21700Kumar** [comment]
hey, i've already done this in my PR earlier.. so it might just get repititive

**Comment by nlok5923** [comment]
But currently this change hadn't reflected in codebase also I hadn't seen any or with these changes that's why I made a pr.

**Comment by Devesh21700Kumar** [comment]
> But currently this change hadn't reflected in codebase also I hadn't seen any or with these changes that's why I made a pr.

yeah my PR had some stuff regarding relative imports so it was held on review.. it was to be merged

**Review by tewarig — COMMENTED** [review]
this seems to be quite similar to #31

**Comment by Devesh21700Kumar** [comment]
> this seems to be quite similar to #31

yes exactly..

**Pull request closed without merging**
