### PR TITLE
Add .prettierrc file fixes #56

### LINKED ISSUE #56: Adding a .prettierrc file
**Why?**
- since many developers around the world are going to collaborate on this wonderful organisation/repo. Everyone should follow some convention.
- on the plus side, it avoids unnecessary spaces, lines, indentations,  No need to discuss style in code review, which Saves you time and energy.

**Why I am opening this issue:-**
- Because I faced problems when I added this repo to my vscode editor. since settings of writing code are as per developer to developer, code unnecessary jumps from one line to another, making GitHub noticing it and adding insertion and deletion count, making the task of maintainers hard.

**Solution:**
- just add a .prettierrc file to the project and voila! All developers are united into a single convention.

### PR DESCRIPTION
**Pull request by jugshaurya**
fixes #56

### CODE REVIEW

**Review by tewarig — APPROVED** [review]

**Comment by pranshuchittora** [comment]
Can you setup Husky with Prettier in this PR?
Later you can do ESLint (later because we need to fix the guidelines before that via an RFC)

**Comment by jugshaurya** [comment]
> Can you setup Husky with Prettier in this PR?
> Later you can do ESLint (later because we need to fix the guidelines before that via an RFC)

Yes sure @pranshuchittora, actually was working on it. Will add husky with prettier

And will add eslint to the project as well.

**Review by jugshaurya — COMMENTED** [review]
Added Husky and prettier for consistent styling across the codebase.
- Imp: already ran prettier over all the files in the src directory via npm run format.
- added format script for future reference
- now complete codebase is consistent with styling via prettier.
- and bad commits protected via husky.

**Files added:**
- .prettierrc
- .prettierignore
- .vscode/recommendation.json [added prettier for contributor to recommend the prettier extension in vscode]

**Comment by jugshaurya** [comment]
@pranshuchittora please review

**Comment by jugshaurya** [comment]
> Added Husky and prettier for consistent styling across the codebase.
> 
> * Imp: already ran prettier over all the files in the src directory via npm run format.
> * added format script for future reference
> * now complete codebase is consistent with styling via prettier.
> * and bad commits protected via husky.

@pranshuchittora please review

**Comment by jugshaurya** [comment]
Also I want to work on adding eslint to project. Let me know when guideline rfc is updated. Will create a issue and pr for same as soon as you update me. Thanks.

**Comment by pranshuchittora** [comment]
LGTM  :)
Thanks

**Pull request merged**
