### PR TITLE
fix [ButtonGroup]: onPress does not select button and updates selectedIndex

### LINKED ISSUE #77: ButtonGroup: onPress does not select button and updates selectedIndex
Screen Recording of the issue:
https://www.loom.com/share/2f1d77cf8d8a469faba06b5c242071f4

**Expected behavior (Required)**
After pressing the button it should be selected (if not disabled)

### PR DESCRIPTION
**Pull request by ankushdutt**
fixes #77

### CODE REVIEW

**Comment by ankushdutt** [comment]
Removed unnecessary commits from PR #78 (closed)

**Review by shivambalwani — APPROVED** [review]

**Review by Uyadav207 — APPROVED** [review]
Good to merge.

**Comment by pranshuchittora** [comment]
LGTM

**Comment by pranshuchittora** [comment]
Thanks @Uyadav207 & @shivambalwani for reviewing.

**Pull request merged**
