### PR TITLE
PWA logo icons now fix

### PR DESCRIPTION
**Pull request by tstariqul**
Issues #48

### CODE REVIEW

**Review by Uyadav207 — CHANGES_REQUESTED** [review]
@tstariqul, Please update your `package.json` file from upstream. As it is creating merge conflict.

**Comment by Uyadav207** [comment]
@tstariqul, If you don't know how to do it... feel free to tag me here.

**Comment by Uyadav207** [comment]
This seems similar to #49 @tstariqul

**Comment by tstariqul** [comment]
@Uyadav207 yes bro I think you can do it.

**Comment by Uyadav207** [comment]
> @Uyadav207 yes bro I think you can do it.

@tstariqul, Didn't get you ??

- I was saying that the PR for the issue is already been merged, Please try resolving an open issue...

**Pull request closed without merging**
