### PR TITLE
Feature:  Added prop explorer to Components

### PR DESCRIPTION
**Pull request by tewarig**
**What kind of change does this PR introduce?**

this pr adds prop explorer to these components..
- tooltip
- socialIcon
- text
- slider
- SearchBar
- pricing
- item list
- input
- image
- header
- divider
- card
- Bottom Sheet

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

this pr solves #66 

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by Uyadav207** [comment]
@tewarig, `I have already done this please don't repeat the PR, this will increase maintainers' workload. requesting you to have a look at previously raised issues so that you can save yourself from extra and tedious work.
I hope you got me.`
Thank you. 

#43 was my issue... please cooperate.

**Comment by tewarig** [comment]
oh I didn't saw that issue.

**Comment by Uyadav207** [comment]
> oh I didn't saw that issue.

I thought that :)  .... No worry brother, it happens...✌️

**Comment by tewarig** [comment]
> > oh I didn't saw that issue.
> 
> I thought that :) .... No worry brother, it happens...

can I leave this pr open? the components on your and mine pr different.

**Comment by Uyadav207** [comment]
Try to find other bugs in the application and don't forget to get in touch. if needed any help @tewarig, would love to help you.

**Comment by tewarig** [comment]
> Try to find other bugs in the application and don't forget to get in touch. if needed any help @tewarig, would love to help you.

sure

**Comment by Uyadav207** [comment]
> > > oh I didn't saw that issue.
> > 
> > 
> > I thought that :) .... No worry brother, it happens...
> 
> can I leave this pr open? the components on your and mine pr different.

Ohh... actually I have made the changes for every component.... but breaking it into pieces to avoid merge conflicts.

**Pull request closed without merging**
