### PR TITLE
Chore(warnings): Rectification of code by removing all (jsx-A11y) warnings

### PR DESCRIPTION
**Pull request by Uyadav207**
**Warnings earlier**

- `alt prop was null for images`
- `jsx-A11y` (span tag to be used for emojis)
- `target= _blank without rel= noopener noreferrer`

### CODE REVIEW

**Review by tewarig — COMMENTED** [review]
I think this pr comes under #3  .
Awesome work @Uyadav207 
but rewriting handleDrawerToggle does not seem to be useful in  src/containers/Drawer/index.jsx

**Comment by Uyadav207** [comment]
No @tewarig I have made new branch for this commit .... they are the previous ones... 😅

Thanks for your concern✌️

**Comment by Uyadav207** [comment]
And it do not comes under #3 because i haven't done any...

- Folder restructuring 
- Styling


Just removed ⚠️ warnings

**Comment by tewarig** [comment]
> And it do not comes under #3 because i haven't done any...
> 
> * Folder restructuring
> * Styling
> 
> Just removed  warnings

still, you are improving the quality of code... . sweat_smile

**Comment by Uyadav207** [comment]
> still, you are improving the quality of code...  😅
> 
> 
> 
> 

😅

**Comment by pranshuchittora** [comment]
Resolve the conflicts & clicking on the Playground in the drawer in the mobile more should close the drawer, can you fix that as well ?

Screenshot from 2021-03-12 20-27-21

**Comment by Uyadav207** [comment]
@pranshuchittora ok I will try to fix it.

**Comment by Uyadav207** [comment]
@pranshuchittora, I got the reason for this conflict... The PR #22 is merged ... before i.e why this or is causing merge conflict. 

I will be making changes sooner.

**Comment by Uyadav207** [comment]
@pranshuchittora, I might need to reopen this. **Please Try to merge it ASAP**

**Reason for conflicts**

- The complete **stylesheet has been changed**. (max 2-3 components).
- The PR you merge #22, has converted all style props to modules. 
-  So that's why my PR is conflicting.

**Solution**

- Best one : (need to open a new PR)
- Average : ( Have to match **diff** ) (Tedious)

**Comment by Uyadav207** [comment]
i have made another PR,  #47 ... please close this.

**Pull request closed without merging**
