### PR TITLE
CheckBox Enhancements: fix checkbox not checking, right not working, leftIcon, add description for all props

### PR DESCRIPTION
**Pull request by ankushdutt**
fixes: #64 

* Update code to enable checkbox check on clicking
* increased width of container so that checking of right and center props have visible changes
* Added descriptions for all props
* Removed leftIcon prop (not supported by CheckBox component)

Recording after fixes: https://www.loom.com/share/514d5d70dec54c2fb8bf4ac16a64399f

Edited:
New recording: https://www.loom.com/share/e8540f356ab74f159105143643fb4856

### CODE REVIEW

**Comment by ankushdutt** [comment]
Removed center and right props. See discussion here: https://github.com/react-native-elements/react-native-elements/pull/2849

**Comment by ankushdutt** [comment]
There was no porblem with the props, it seems to be working fine when the container width is large enough. I have added them back and increased the width of the container. We can now merge this one now @pranshuchittora.

**Comment by pranshuchittora** [comment]
Pls resolve the conflicts.

**Comment by piyushdevOP** [comment]
@ankushdutt Hey buddy the fix looks working. What are the conflicts arising?

**Comment by pranshuchittora** [comment]
LGTM :)

**Comment by pranshuchittora** [comment]
Thanks

**Pull request merged**
