### PR TITLE
🔥( Hot-Fix ):  fixes UI breaking by error rendering component of (react-view) in playground area. 

### LINKED ISSUE #75: 🐛 Bug:  Error log is unaligned and breaking the UI of playground. (Need to make a hot-fix) for all components.
**Explain what you did (Required)**

- I intentionally tried to create a compilation error on the playground.
- The error popup was found breaking UI for the playground application.

**Expected behavior (Required)**

- The error component should not break the UI.
- This will cause the user un-comfortable while using the playground web app.

**Describe the bug (Required)**

- The bug is breaking the UI of the `Playground`.

**To Reproduce (Required)**

https://react-native-elements.js.org/#/icon'

- Steps
1. Go to 'https://react-native-elements.js.org/#/icon'
2. Try to create typos 'in the text editor of the playground'.
3. Scroll down to 'Look to the top error components'

**Screenshots (Required)**

Screenshot from 2021-03-16 12-32-48

Expected: (screenshot)
 
Screenshot from 2021-03-16 12-43-31

@pranshuchittora, and @flyingcircle... I have started working on the bug to be fixed as early as possible?

**Any suggestions are welcome** @flyingcircle @pranshuchittora

### PR DESCRIPTION
**Pull request by Uyadav207**
**What kind of change does this PR introduce?**

- 🔥( Hot-Fix ):  fixes UI breaking by error rendering component of (react-view) in the playground area. 

**Did you add tests for your changes?**

- Not required(tested manually)

**If relevant, did you update the documentation?**

- Not required

**Summary**

- The error component should not break the UI.
- This will cause the user un-comfortable while using the playground web app.
- Fixes #75 

**Does this PR introduce a breaking change?**

- No breaking changes are involved.

**Other information** (screenshot after the fix)

Screenshot from 2021-03-16 12-43-31

### CODE REVIEW

**Comment by Uyadav207** [comment]
@flyingcircle and @pranshuchittora done with the fix... Kindly review it...

**Comment by pranshuchittora** [comment]
Too many files 😕 
The branch of this PR seems to be forked from the previous PR.

**Comment by Uyadav207** [comment]
I have made a new branch pushed the changes.... Didn't fork the previous branch @pranshuchittora shu

**Comment by Uyadav207** [comment]
I think upper commits are related to the previous commit logg .... nothings to with this PR..

Please have a look

**Comment by pranshuchittora** [comment]
Can you pull the latest changes from the master

**Comment by Uyadav207** [comment]
I will do it and have to make a new pr... please try to merge it sir... before any further conflict.. :)

**Comment by Uyadav207** [comment]
Just a doubt ...  @pranshuchittora what about #53 and #57... as you told the changes are made in #15 but I have seen that .....the changes in #15... are only for limited components max 5 components so... may I raise a pr for left overs

**Comment by Uyadav207** [comment]
@pranshuchittora, after merging #15...

getting this error.

Screenshot from 2021-03-20 08-57-28

**Comment by Uyadav207** [comment]
@pranshuchittora, sir... in #15... the changes made in ... Content folder  in `.jsx files`

```js

import PropDrawer from "../../components/PropDrawer";
import Playground from "./searchbar.playground.jsx";

const Content = lazy(() => importMDX("../Props/searchbar.md"));

export default function SearchBarPlayground() {
  return (
    <div>
      <Playground />
      <Suspense fallback={<div>Loading...</div>}>
        <PropDrawer>
          <Content />
        </PropDrawer>
      </Suspense>
    </div>
  );
}

```

Are these chunks of code are repeated allover... and this is making a problem in compiling the web app...

**Comment by Uyadav207** [comment]
Made a New PR.. Resolving the merge conflict... @pranshuchittora ... #87

**Pull request closed without merging**
